### PR TITLE
Added Docker support.

### PR DESCRIPTION
**Pull request by keanuplayz**
This pull request adds:
- A `Dockerfile` located at `/`
- Automated builds at [Docker Hub](https://hub.docker.com/repository/docker/keanucode/travbot-v3)

### CODE REVIEW

**Review by WatDuhHekBro — APPROVED** [review]
Works fine. Though there are a few gotchas that I'll leave as a comment here for the future (at least on a Windows environment):
- For the command line setup to work, you have to run Docker in interactive mode (`docker run -i keanucode/travbot-v3`). Otherwise, anything you type will be part of the command line itself and not part of the Docker program.
- Inquirer seems to act weird, duplicating lines. Might want to look into this.
- Chalk and its colors don't seem to work. It doesn't affect the program, but could be something to look into.
2020-09-10 02_05_47-Window

**Comment by keanuplayz** [comment]
@WatDuhHekBro 
> For the command line setup to work, you have to run Docker in interactive mode

This is known, I'll have to add it to the `README`.

> Inquirer seems to act weird, duplicating lines. Might want to look into this.

Do you need to enter info twice when Inquirer duplicates a line?

> Chalk and its colors don't seem to work.

This is a known issue. Docker outputs raw info to `stdin` and `stdout`.

Try running with `--colors` or set environment variable `FORCE_COLOR` to `1` (e.g. `-e FORCE_COLOR=1`)

**Comment by WatDuhHekBro** [comment]
As for Inquirer duplicating lines, I didn't need to enter info twice, it just displayed twice.
After some more testing, the last two issues can be fixed by attaching a pseudo terminal (`-t`). Now Inquirer and the colors work as expected.

**Review by lexisother — APPROVED** [review]
Seems to be working well! 👍

**Review by WatDuhHekBro — APPROVED** [review]
Works well for the most part. One last issue to look into is that the way to update containers is to create a new one from the latest image, meaning that any data stored in that container won't automatically transfer over.

**Comment by WatDuhHekBro** [comment]
Alright, I think I've got a hold on volumes. Because they're external, you can use a volume for multiple containers, especially useful when upgrading a bot to another version. `docker volume` manages commands, then when you're ready, `docker run -it --mount source=<volume>,target=/data <image>` to link a named volume to a container. With that out of the way, everything's set.

**Pull request merged**
