### PR TITLE
Ported over the eco command from TravBot 2

### PR DESCRIPTION
**Pull request by WatDuhHekBro**

### CODE REVIEW

**Comment by WatDuhHekBro** [comment]
We should also agree upon a formatting scheme (what the code should look like) and method (do we run `npm run format` or use a git hook?). There was a merge conflict in `package.json` and the only reason why was because of line endings (I'm not sure whether the original file used LF or CRLF).

**Comment by keanuplayz** [comment]
I'm gonna go ahead and say that an `npm` script would be best. I have bad experience with Git hooks. Last time I tried setting that stuff up I nearly had a mental breakdown.

**Comment by keanuplayz** [comment]
Ready for review?

**Comment by WatDuhHekBro** [comment]
Yeah

**Review by keanuplayz — APPROVED** [review]
Everything looking squeaky clean. I say it's ready to merge.

**Pull request merged**
